title:       'МАЙКА/СТУДИЯ'
author:      'maykastudio.ru'
copyright:   'maykastudio.ru'
description: 'жанр, портрет, свадьба, свадебная фотография, пейзаж, натюрморт, фотограф, maykastudio, майкастудио'
keywords:    'жанр, портрет, свадьба, свадебная фотография, пейзаж, натюрморт, фотограф, maykastudio, майкастудио'
url:         'http://maykastudio.ru'
baseurl:     ''
google_verification: 'DEsPuVb8zjMrrdeJT3elZo090-SgKa3_PnrQcjEBGTo'

markdown: kramdown
highlighter: pygments
permalink: /:title

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jemoji
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
